// <copyright file="Category.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

namespace Endjin.FreeAgent.Domain;

/// <summary>
/// Represents an accounting category in the FreeAgent system.
/// </summary>
/// <remarks>
/// <para>
/// Categories classify financial transactions for accounting and tax reporting purposes.
/// Each category corresponds to a nominal code in the chart of accounts and has specific
/// tax treatment rules for sales tax calculations.
/// </para>
/// <para>
/// Categories are organized into groups with specific nominal code ranges:
/// <list type="bullet">
/// <item>Income: 001-049</item>
/// <item>Cost of Sales: 096-199</item>
/// <item>Admin Expenses: 200-399</item>
/// <item>Current Assets: 671-720</item>
/// <item>Liabilities: 731-780</item>
/// <item>Equities: 921-960</item>
/// </list>
/// </para>
/// <para>
/// FreeAgent provides predefined categories based on company type, but users can also create,
/// update, and delete custom categories via the API. Update and delete operations are restricted
/// to empty categories (categories with no associated transactions).
/// </para>
/// <para>
/// Note: Some fields are read-only and cannot be modified through the API:
/// <list type="bullet">
/// <item><see cref="Url"/> - Automatically generated by the system</item>
/// <item><see cref="GroupDescription"/> - Determined by the nominal code range</item>
/// </list>
/// </para>
/// <para>
/// API Endpoint: /v2/categories
/// </para>
/// </remarks>
/// <seealso cref="Expense"/>
/// <seealso cref="Invoice"/>
/// <seealso cref="CategoryGroupType"/>
/// <seealso cref="AutoSalesTaxRateType"/>
public record Category
{
    /// <summary>
    /// Gets the unique URI identifier for this category.
    /// </summary>
    /// <value>
    /// A URI that uniquely identifies this category in the FreeAgent system.
    /// This URI is used when assigning categories to transactions.
    /// </value>
    /// <remarks>
    /// This field is read-only and automatically generated by the FreeAgent system.
    /// </remarks>
    [JsonPropertyName("url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Uri? Url { get; init; }

    /// <summary>
    /// Gets the nominal ledger code for this category.
    /// </summary>
    /// <value>
    /// The accounting nominal code that corresponds to this category in the chart of accounts.
    /// </value>
    [JsonPropertyName("nominal_code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? NominalCode { get; init; }

    /// <summary>
    /// Gets the descriptive name of the category.
    /// </summary>
    /// <value>
    /// A human-readable description of what types of transactions this category represents.
    /// </value>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }

    /// <summary>
    /// Gets the group description for this category.
    /// </summary>
    /// <value>
    /// The name of the category group this category belongs to, determined by the nominal code range.
    /// </value>
    /// <remarks>
    /// This field is read-only and automatically determined based on the nominal code.
    /// It is only present in responses for income and spending categories.
    /// </remarks>
    [JsonPropertyName("group_description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? GroupDescription { get; init; }

    /// <summary>
    /// Gets the tax reporting name for this category.
    /// </summary>
    /// <value>
    /// The name used when this category appears on tax returns and tax reports.
    /// </value>
    [JsonPropertyName("tax_reporting_name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TaxReportingName { get; init; }

    /// <summary>
    /// Gets the automatic sales tax rate applied to this category.
    /// </summary>
    /// <value>
    /// The default VAT/GST rate classification applied to transactions in this category when automatic tax calculation is enabled.
    /// Valid values: "Outside of the scope of VAT", "Zero rate", "Reduced rate", "Standard rate", "Exempt" (income only).
    /// </value>
    /// <remarks>
    /// This field is only applicable to income and spending categories (income, cost_of_sales, admin_expenses).
    /// The "Exempt" value is only valid for income categories.
    /// </remarks>
    [JsonPropertyName("auto_sales_tax_rate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AutoSalesTaxRate { get; init; }

    /// <summary>
    /// Gets a value indicating whether expenses in this category are allowable for tax purposes.
    /// </summary>
    /// <value>
    /// <c>true</c> if expenses in this category are tax deductible; otherwise, <c>false</c>.
    /// </value>
    [JsonPropertyName("allowable_for_tax")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowableForTax { get; init; }

    /// <summary>
    /// Gets the URI of the associated bank account for sub-account categories.
    /// </summary>
    /// <value>
    /// The bank account URI for 750-x nominal code sub-accounts; otherwise, <c>null</c>.
    /// </value>
    [JsonPropertyName("bank_account")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Uri? BankAccount { get; init; }

    /// <summary>
    /// Gets the URI of the associated capital asset type for sub-account categories.
    /// </summary>
    /// <value>
    /// The capital asset type URI for 601-x to 607-x nominal code sub-accounts; otherwise, <c>null</c>.
    /// </value>
    [JsonPropertyName("capital_asset_type")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Uri? CapitalAssetType { get; init; }

    /// <summary>
    /// Gets the URI of the associated stock item for sub-account categories.
    /// </summary>
    /// <value>
    /// The stock item URI for 609-x nominal code sub-accounts; otherwise, <c>null</c>.
    /// </value>
    [JsonPropertyName("stock_item")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Uri? StockItem { get; init; }

    /// <summary>
    /// Gets the URI of the associated hire purchase for sub-account categories.
    /// </summary>
    /// <value>
    /// The hire purchase URI for 792-x to 793-x nominal code sub-accounts; otherwise, <c>null</c>.
    /// </value>
    [JsonPropertyName("hire_purchase")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Uri? HirePurchase { get; init; }

    /// <summary>
    /// Gets the URI of the associated user for sub-account categories.
    /// </summary>
    /// <value>
    /// The user URI for 900-x to 910-x nominal code sub-accounts; otherwise, <c>null</c>.
    /// </value>
    [JsonPropertyName("user")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Uri? User { get; init; }
}