// <copyright file="FreeAgentJsonContext.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using System.Collections.Immutable;
using System.Text.Json.Serialization;
using Endjin.FreeAgent.Domain;

namespace Endjin.FreeAgent.Client;

/// <summary>
/// JSON source generation context for FreeAgent API types, providing compile-time JSON serialization metadata.
/// </summary>
/// <remarks>
/// <para>
/// This class uses .NET's source generation feature to generate JSON serialization code at compile time
/// rather than using reflection at runtime. This provides several benefits:
/// <list type="bullet">
/// <item><description>Improved performance - no reflection overhead during serialization/deserialization</description></item>
/// <item><description>Reduced memory allocation - serialization metadata is generated once at compile time</description></item>
/// <item><description>AOT (Ahead-of-Time) compilation support - works with Native AOT and trimming</description></item>
/// <item><description>Better startup time - no runtime code generation needed</description></item>
/// <item><description>Smaller deployment size - only referenced types are included</description></item>
/// </list>
/// </para>
/// <para>
/// The context includes all FreeAgent API types used for requests and responses, covering:
/// <list type="bullet">
/// <item><description>Root wrapper types (e.g., ContactRoot, InvoiceRoot) for API responses</description></item>
/// <item><description>Domain model types (e.g., Contact, Invoice) for entities</description></item>
/// <item><description>Supporting types for bank transactions, reports, tax returns, etc.</description></item>
/// </list>
/// </para>
/// <para>
/// This context is used by <see cref="SharedJsonOptions.SourceGenOptions"/> to provide
/// source-generated serialization throughout the library. The serialization options are configured
/// to match the FreeAgent API requirements (camelCase naming, ignore null values, etc.).
/// </para>
/// </remarks>
/// <seealso cref="SharedJsonOptions"/>
/// <seealso cref="JsonSerializerContext"/>
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNameCaseInsensitive = true,
    WriteIndented = false,
    AllowTrailingCommas = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
// Root types for API responses
[JsonSerializable(typeof(AttachmentRoot))]
[JsonSerializable(typeof(BalanceSheetRoot))]
[JsonSerializable(typeof(BalanceSheetAccount))]
[JsonSerializable(typeof(CapitalAssetsSection))]
[JsonSerializable(typeof(AssetsSection))]
[JsonSerializable(typeof(LiabilitiesSection))]
[JsonSerializable(typeof(OwnersEquitySection))]
[JsonSerializable(typeof(BankAccountRoot))]
[JsonSerializable(typeof(BankAccountsRoot))]
[JsonSerializable(typeof(BankStatementUploadRoot))]
[JsonSerializable(typeof(BankStatementUploadResponseRoot))]
[JsonSerializable(typeof(BankTransactionExplanationRoot))]
[JsonSerializable(typeof(BankTransactionExplanationsRoot))]
[JsonSerializable(typeof(BankTransactionRoot))]
[JsonSerializable(typeof(BankTransactionsRoot))]
[JsonSerializable(typeof(BankTransactionUploadRoot))]
[JsonSerializable(typeof(BillRoot))]
[JsonSerializable(typeof(BillsRoot))]
[JsonSerializable(typeof(BusinessCategoriesRoot))]
[JsonSerializable(typeof(CapitalAssetRoot))]
[JsonSerializable(typeof(CapitalAssetsRoot))]
[JsonSerializable(typeof(CapitalAssetTypeRoot))]
[JsonSerializable(typeof(CapitalAssetTypesRoot))]
[JsonSerializable(typeof(CashFlowRoot))]
[JsonSerializable(typeof(CashFlowDirection))]
[JsonSerializable(typeof(CashFlowMonthly))]
[JsonSerializable(typeof(CategoriesRoot))]
[JsonSerializable(typeof(CategoryRoot))]
[JsonSerializable(typeof(CategoryCreateRequestRoot))]
[JsonSerializable(typeof(CategoryUpdateRequestRoot))]
[JsonSerializable(typeof(CisBandsResponse))]
[JsonSerializable(typeof(CompanyRoot))]
[JsonSerializable(typeof(ContactRoot))]
[JsonSerializable(typeof(ContactsRoot))]
[JsonSerializable(typeof(CorporationTaxReturnRoot))]
[JsonSerializable(typeof(CorporationTaxReturnsRoot))]
[JsonSerializable(typeof(FinalAccountsReportRoot))]
[JsonSerializable(typeof(FinalAccountsReportsRoot))]
[JsonSerializable(typeof(HirePurchaseRoot))]
[JsonSerializable(typeof(HirePurchasesRoot))]
[JsonSerializable(typeof(CreditNoteRoot))]
[JsonSerializable(typeof(CreditNotesRoot))]
[JsonSerializable(typeof(CreditNoteReconciliationRoot))]
[JsonSerializable(typeof(CreditNoteReconciliationsRoot))]
[JsonSerializable(typeof(CreditNoteEmailRoot))]
[JsonSerializable(typeof(CreditNotePdfRoot))]
[JsonSerializable(typeof(CurrenciesRoot))]
[JsonSerializable(typeof(DepreciationProfilesRoot))]
[JsonSerializable(typeof(EmailAddressesRoot))]
[JsonSerializable(typeof(EstimateRoot))]
[JsonSerializable(typeof(EstimatesRoot))]
[JsonSerializable(typeof(EstimateEmailRoot))]
[JsonSerializable(typeof(EstimatePdfRoot))]
[JsonSerializable(typeof(EstimateItemRoot))]
[JsonSerializable(typeof(EstimateDefaultAdditionalTextRoot))]
[JsonSerializable(typeof(ExpenseRoot))]
[JsonSerializable(typeof(ExpensesRoot))]
[JsonSerializable(typeof(InvoiceRoot))]
[JsonSerializable(typeof(InvoicesRoot))]
[JsonSerializable(typeof(InvoiceEmailRoot))]
[JsonSerializable(typeof(InvoicePdfRoot))]
[JsonSerializable(typeof(InvoiceTimelineRoot))]
[JsonSerializable(typeof(InvoiceDefaultAdditionalTextRoot))]
[JsonSerializable(typeof(JournalSetRoot))]
[JsonSerializable(typeof(JournalSetsRoot))]
[JsonSerializable(typeof(MileageRoot))]
[JsonSerializable(typeof(MileagesRoot))]
[JsonSerializable(typeof(MileageSettingsRoot))]
[JsonSerializable(typeof(NoteItem))]
[JsonSerializable(typeof(NoteRoot))]
[JsonSerializable(typeof(NotesRoot))]
[JsonSerializable(typeof(OpeningBalanceRoot))]
[JsonSerializable(typeof(PayrollProfilesRoot))]
[JsonSerializable(typeof(PayrollYearRoot))]
[JsonSerializable(typeof(PayrollPeriodRoot))]
[JsonSerializable(typeof(PayrollPeriod))]
[JsonSerializable(typeof(PriceListItemRoot))]
[JsonSerializable(typeof(PriceListItemsRoot))]
[JsonSerializable(typeof(ProfitAndLossRoot))]
[JsonSerializable(typeof(ProfitAndLoss))]
[JsonSerializable(typeof(ProfitAndLossDeduction))]
[JsonSerializable(typeof(List<ProfitAndLossDeduction>))]
[JsonSerializable(typeof(ProjectRoot))]
[JsonSerializable(typeof(ProjectsRoot))]
[JsonSerializable(typeof(PropertiesRoot))]
[JsonSerializable(typeof(PropertyRoot))]
[JsonSerializable(typeof(PurchaseAgedCreditorsRoot))]
[JsonSerializable(typeof(RecurringInvoiceRoot))]
[JsonSerializable(typeof(RecurringInvoicesRoot))]
[JsonSerializable(typeof(SalesAgedDebtorsRoot))]
[JsonSerializable(typeof(SalesTaxRatesRoot))]
[JsonSerializable(typeof(SalesTaxPeriodRoot))]
[JsonSerializable(typeof(SalesTaxPeriodsRoot))]
[JsonSerializable(typeof(SelfAssessmentReturnRoot))]
[JsonSerializable(typeof(SelfAssessmentReturnsRoot))]
[JsonSerializable(typeof(SelfAssessmentReturnFilingRoot))]
[JsonSerializable(typeof(StatementUploadRoot))]
[JsonSerializable(typeof(StockItemRoot))]
[JsonSerializable(typeof(StockItemsRoot))]
[JsonSerializable(typeof(TaskRoot))]
[JsonSerializable(typeof(TasksRoot))]
[JsonSerializable(typeof(TaxTimelineRoot))]
[JsonSerializable(typeof(TimeslipsRoot))]
[JsonSerializable(typeof(TrialBalanceRoot))]
[JsonSerializable(typeof(UserRoot))]
[JsonSerializable(typeof(UsersRoot))]
[JsonSerializable(typeof(VatReturnRoot))]
[JsonSerializable(typeof(VatReturnsRoot))]
[JsonSerializable(typeof(VatReturnFilingRoot))]
[JsonSerializable(typeof(WebhookRoot))]
[JsonSerializable(typeof(WebhooksRoot))]
// Domain models (needed for serialization of request bodies)
[JsonSerializable(typeof(AnnualAccountingPeriod))]
[JsonSerializable(typeof(Attachment))]
[JsonSerializable(typeof(BankAccount))]
[JsonSerializable(typeof(BankTransaction))]
[JsonSerializable(typeof(BankTransactionExplanation))]
[JsonSerializable(typeof(BankTransactionUpload))]
[JsonSerializable(typeof(Bill))]
[JsonSerializable(typeof(BillAttachment))]
[JsonSerializable(typeof(BillItem))]
[JsonSerializable(typeof(CapitalAsset))]
[JsonSerializable(typeof(Category))]
[JsonSerializable(typeof(CategoryCreateRequest))]
[JsonSerializable(typeof(CategoryUpdateRequest))]
[JsonSerializable(typeof(CategoryGroupType))]
[JsonSerializable(typeof(CategoryGroupType?))]
[JsonSerializable(typeof(AutoSalesTaxRateType))]
[JsonSerializable(typeof(AutoSalesTaxRateType?))]
[JsonSerializable(typeof(SalesTaxRegistrationStatus))]
[JsonSerializable(typeof(SalesTaxRegistrationStatus?))]
[JsonSerializable(typeof(CisBand))]
[JsonSerializable(typeof(Domain.Company))]
[JsonSerializable(typeof(CompanyType))]
[JsonSerializable(typeof(CompanyType?))]
[JsonSerializable(typeof(Contact))]
[JsonSerializable(typeof(CorporationTaxReturn))]
[JsonSerializable(typeof(CorporationTaxFilingStatus))]
[JsonSerializable(typeof(CorporationTaxFilingStatus?))]
[JsonSerializable(typeof(CorporationTaxPaymentStatus))]
[JsonSerializable(typeof(CorporationTaxPaymentStatus?))]
[JsonSerializable(typeof(FinalAccountsReport))]
[JsonSerializable(typeof(FinalAccountsFilingStatus))]
[JsonSerializable(typeof(FinalAccountsFilingStatus?))]
[JsonSerializable(typeof(HirePurchase))]
[JsonSerializable(typeof(EcStatus))]
[JsonSerializable(typeof(EcStatus?))]
[JsonSerializable(typeof(SalesTaxStatus))]
[JsonSerializable(typeof(SalesTaxStatus?))]
[JsonSerializable(typeof(RebillType))]
[JsonSerializable(typeof(RebillType?))]
[JsonSerializable(typeof(RecurringPattern))]
[JsonSerializable(typeof(RecurringPattern?))]
[JsonSerializable(typeof(VehicleType))]
[JsonSerializable(typeof(VehicleType?))]
[JsonSerializable(typeof(EngineType))]
[JsonSerializable(typeof(EngineType?))]
[JsonSerializable(typeof(CreditNote))]
[JsonSerializable(typeof(CreditNoteItem))]
[JsonSerializable(typeof(CreditNoteReconciliation))]
[JsonSerializable(typeof(CreditNoteEmailWrapper))]
[JsonSerializable(typeof(CreditNotePdf))]
[JsonSerializable(typeof(Estimate))]
[JsonSerializable(typeof(EstimateEmail))]
[JsonSerializable(typeof(EstimateEmailWrapper))]
[JsonSerializable(typeof(EstimateItem))]
[JsonSerializable(typeof(EstimatePdf))]
[JsonSerializable(typeof(EstimateDefaultAdditionalText))]
[JsonSerializable(typeof(EmailAttachment))]
[JsonSerializable(typeof(List<EmailAttachment>))]
[JsonSerializable(typeof(Expense))]
[JsonSerializable(typeof(List<Expense>))]
[JsonSerializable(typeof(ExpenseAttachment))]
[JsonSerializable(typeof(Invoice))]
[JsonSerializable(typeof(InvoiceEmail))]
[JsonSerializable(typeof(InvoiceEmailWrapper))]
[JsonSerializable(typeof(InvoiceItem))]
[JsonSerializable(typeof(List<InvoiceItem>))]
[JsonSerializable(typeof(InvoicePdf))]
[JsonSerializable(typeof(InvoiceTimelineEntry))]
[JsonSerializable(typeof(List<InvoiceTimelineEntry>))]
[JsonSerializable(typeof(InvoiceDefaultAdditionalText))]
[JsonSerializable(typeof(JournalSet))]
[JsonSerializable(typeof(JournalEntry))]
[JsonSerializable(typeof(Mileage))]
[JsonSerializable(typeof(MileageSettings))]
[JsonSerializable(typeof(EngineTypeAndSizeOption))]
[JsonSerializable(typeof(MileageRateOption))]
[JsonSerializable(typeof(MileageRatesValue))]
[JsonSerializable(typeof(VehicleMileageRate))]
[JsonSerializable(typeof(Dictionary<string, string[]>))]
[JsonSerializable(typeof(List<DateTime>))]
[JsonSerializable(typeof(List<DateTimeOffset>))]
[JsonSerializable(typeof(OpeningBalance))]
[JsonSerializable(typeof(PaymentMethods))]
[JsonSerializable(typeof(PayrollProfile))]
[JsonSerializable(typeof(ImmutableList<PayrollProfile>))]
[JsonSerializable(typeof(PayrollPayment))]
[JsonSerializable(typeof(Payslip))]
[JsonSerializable(typeof(PriceListItem))]
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(Property))]
[JsonSerializable(typeof(ImmutableList<Property>))]
[JsonSerializable(typeof(RecurringInvoice))]
[JsonSerializable(typeof(ImmutableList<RecurringInvoice>))]
[JsonSerializable(typeof(List<RecurringInvoice>))]
[JsonSerializable(typeof(SalesTaxRate))]
[JsonSerializable(typeof(SalesTaxPeriod))]
[JsonSerializable(typeof(StockItem))]
[JsonSerializable(typeof(Task))]
[JsonSerializable(typeof(TaxTimelineItem))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(Webhook))]
public partial class FreeAgentJsonContext : JsonSerializerContext
{
}